version: "3.8"
services:
  missao-java:
    container_name: crud-usuario
    image: gustavo-fior/missao-java:latest
    ports:
      - 8080:8080
    networks:
      - minha-brigde

networks:
  minha-brigde:
    driver: bridge
